### PR TITLE
fix/fixes goroutines

### LINKED ISSUE #105: Error starting docker from Frontend Repo
@lazyguru So the fix you pushed last night definitely fixed the original error I was receiving, however now the startup progresses much further but is still failing with the federation container in an unhealthy state:

```
seeder-1      | Running likePost() for entity with ID 10
api-1         | 2024-06-09T23:03:30.913Z DEBUG 1 --- [nio-8080-exec-8] o.s.web.servlet.DispatcherServlet        : POST "/api/v3/user/login", parameters={}
api-1         | 2024-06-09T23:03:30.913Z DEBUG 1 --- [nio-8080-exec-8] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped to com.sublinks.sublinksapi.api.lemmy.v3.user.controllers.UserAuthController#login(HttpServletRequest, Login)
api-1         | 2024-06-09T23:03:30.914Z DEBUG 1 --- [nio-8080-exec-8] m.m.a.RequestResponseBodyMethodProcessor : Read "application/json;charset=UTF-8" to [Login[username_or_email=luke, password=password123, totp_2fa_token=null]]
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container docker-federation-1 is unhealthy
```

### PR DESCRIPTION
**Pull request by devanbenz**
- Adds context for methods that have go functions
- lifts signal channel and timeout ctx out of http server 
- passes shared ctx amongst functions

Fixes #105

### CODE REVIEW

File: internal/http/activity.go [hunk 1]
```diff
@@ -13,6 +13,7 @@ import (
 )
 
 func (server *Server) SetupActivityRoutes() {
+	server.Logger.Info("Setting up activity routes")
```
Comment (lazyguru) [inline internal/http/activity.go:16]: These should all be debug

File: internal/queue/consumer.go [hunk 2]
```diff
@@ -52,7 +53,7 @@ func (q *RabbitQueue) createConsumer(queueData ConsumerQueue) error {
 	return nil
 }
 
-func (q *RabbitQueue) StartConsumer(queueData ConsumerQueue) error {
+func (q *RabbitQueue) StartConsumer(queueData ConsumerQueue, ctx context.Context) error {
```
Comment (lazyguru) [inline internal/queue/consumer.go:56]: Mostly a nitpick, but can we make ctx the first parameter (in all of the methods where you added it)?

File: internal/queue/queue.go [hunk 3]
```diff
@@ -66,13 +79,22 @@ func (q *RabbitQueue) processActors(serviceManager *service.ServiceManager) {
 		},
 	}
 
-	err := q.StartConsumer(actorCQ)
-	if err != nil {
-		q.logger.Fatal("failed starting actor consumer", err)
+	for {
+		select {
+		case <-ctx.Done():
+			q.logger.Warn("actor context canceled")
```
Comment (lazyguru) [inline internal/queue/queue.go:85]: Should this be a warning? Is it a result of CTRL+C? Or is it a result of a failure?  If former, then I think debug is more appropriate.

**Review by lazyguru — CHANGES_REQUESTED** [review]

File: internal/queue/consumer.go [hunk 4]
```diff
@@ -67,16 +68,17 @@ func (q *RabbitQueue) StartConsumer(queueData ConsumerQueue, ctx context.Context
...
 		case message, ok := <-messages:
 			if !ok {
-				q.logger.Warn("consumer channel closed")
+				q.logger.Error("consumer channel closed", errors.New("consumer channel closed"))
 				return errGroup.Wait()
 			}
 			msg := message
 			errGroup.Go(func() error {
 				cbWorker, ok := queueData.RoutingKeys[msg.RoutingKey]
+				q.logger.Info(fmt.Sprintf("consumer got message from routing key: %s", msg.RoutingKey))
```
Comment (lazyguru) [inline internal/queue/consumer.go:81]: This should definitely be debug

File: internal/queue/queue.go [hunk 5]
```diff
@@ -48,12 +50,23 @@ func (q *RabbitQueue) Status() map[string]map[string]bool {
...
+
+	go func() {
+		defer wg.Done()
+		q.logger.Info("starting actor consumer")
+		q.processActors(ctx, serviceManager)
+	}()
+
+	go func() {
+		defer wg.Done()
+		q.logger.Info("starting object consumer")
```
Comment (lazyguru) [inline internal/queue/queue.go:64]: We should either make these both debug, or call this something other than "object" (which I kind of think we should rename in the code anyway, I just don't have a better name right now)

**Review by lazyguru — APPROVED** [review]
